Add form + table view, add prettier, style with Pico CSS
AndreasPB/si-mandatory1 pull request #7
Opened 2022-03-09 18:39 UTC by AndreasPB

2022-03-09 18:40 UTC, AndreasPB commented on api/app/main.py
>  from fastapi import FastAPI
Remove backend stuff from here - It was just to test

2022-03-09 18:41 UTC, AndreasPB commented
Just a heads-up, I ran `pre-commit --all-files` with the new pre-commit settings, so that's why a lot of the files are getting indented/whatever

2022-03-10 17:46 UTC, nullxDEADBEEF requested changes

2022-03-10 17:46 UTC, nullxDEADBEEF commented on api/app/main.py
> +async def find_users():
Ligesom med post_user, lad os holde os til REST navnene(get_user, post_user, delete_user, etc.)

2022-03-10 17:46 UTC, nullxDEADBEEF commented on api/app/main.py
> +async def find_user_by_name(name: str):
Samme som over

2022-03-10 22:34 UTC, AndreasPB commented on api/app/main.py
> +async def find_users():
Done

2022-03-10 22:34 UTC, AndreasPB commented on api/app/main.py
> +async def find_user_by_name(name: str):
Done

2022-03-10 22:38 UTC, AndreasPB commented on api/app/main.py
>  from fastapi import FastAPI
I/we decided tp just leave it... IDK

2022-03-13 00:26 UTC, nullxDEADBEEF approved these changes
:rocket: :guitar:

2022-03-13 00:26 UTC, merged